# All Out War Config



# CORE Villager settings
coreVillagerValue: 5
coreVillagerHealth: 100



# Spawn entityID and price(Emerald)
mobs:
  - name: Zombie
    price: 2
  - name: Skeleton
    price: 4
  - name: Creeper
    price: 8
  - name: Blaze
    price: 20
  - name: CaveSpider
    price: 15
  - name: Enderman
    price: 15
  - name: Ghast
    price: 20
  - name: IronGolem
    price: 30
  - name: Spider
    price: 6
  - name: Witch
    price: 15
  - name: Wither
    price: 64
  - name: Wolf
    price: 32



