name: AllOutWar
main: com.eviltwo.alloutwar.AOW
version: 0.6.5

commands:
   team:
      description: This is a demo command.
      usage: /<command> [create/join/remove] <TeamName>...
      permission: tutorialplugin.basic
      permission-message: You don't have <permission>