name: AllOutWar
main: com.eviltwo.alloutwar.AOW
version: 0.7.6

commands:
   team:
      description: This is a demo command.
      usage: /<command> <create/join/start/leave/remove>...
      permission: alloutwar.admin
      permission-message: You don't have <permission>